# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sm/Downloads/cmake-3.27.7-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/sm/Downloads/cmake-3.27.7-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sm/Desktop/production

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sm/Desktop/production

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/sm/Downloads/cmake-3.27.7-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sm/Desktop/production/CMakeFiles /home/sm/Desktop/production//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sm/Desktop/production/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpeechToText

# Build rule for target.
SpeechToText: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpeechToText
.PHONY : SpeechToText

# fast build rule for target.
SpeechToText/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/build
.PHONY : SpeechToText/fast

STT.o: STT.cpp.o
.PHONY : STT.o

# target to build an object file
STT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/STT.cpp.o
.PHONY : STT.cpp.o

STT.i: STT.cpp.i
.PHONY : STT.i

# target to preprocess a source file
STT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/STT.cpp.i
.PHONY : STT.cpp.i

STT.s: STT.cpp.s
.PHONY : STT.s

# target to generate assembly for a file
STT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/STT.cpp.s
.PHONY : STT.cpp.s

SpeechRecognizer.o: SpeechRecognizer.cpp.o
.PHONY : SpeechRecognizer.o

# target to build an object file
SpeechRecognizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/SpeechRecognizer.cpp.o
.PHONY : SpeechRecognizer.cpp.o

SpeechRecognizer.i: SpeechRecognizer.cpp.i
.PHONY : SpeechRecognizer.i

# target to preprocess a source file
SpeechRecognizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/SpeechRecognizer.cpp.i
.PHONY : SpeechRecognizer.cpp.i

SpeechRecognizer.s: SpeechRecognizer.cpp.s
.PHONY : SpeechRecognizer.s

# target to generate assembly for a file
SpeechRecognizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpeechToText.dir/build.make CMakeFiles/SpeechToText.dir/SpeechRecognizer.cpp.s
.PHONY : SpeechRecognizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SpeechToText"
	@echo "... STT.o"
	@echo "... STT.i"
	@echo "... STT.s"
	@echo "... SpeechRecognizer.o"
	@echo "... SpeechRecognizer.i"
	@echo "... SpeechRecognizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

